{
    parserClass="me.rerere.unocssintellij.lang.parser.UnocssParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Unocss"
    psiImplClassSuffix="Impl"
    psiPackage="me.rerere.unocssintellij.lang.psi"
    psiImplPackage="me.rerere.unocssintellij.lang.psi.impl"

    elementTypeHolderClass="me.rerere.unocssintellij.lang.psi.UnocssTypes"
    elementTypeClass="me.rerere.unocssintellij.lang.UnocssElementType"
    tokenTypeClass="me.rerere.unocssintellij.lang.UnocssTokenType"
}

unocssFile ::= classValue*

classValue ::= CLASSNAME (WHITESPACE CLASSNAME)*